name: Project Automation

on:
  issues:
    types: [opened, reopened, closed]
  pull_request:
    types: [opened, reopened, closed]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/SManuelDv/projects/9
          github-token: ${{ secrets.GITHUB_TOKEN }}

  update_project_status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.payload.issue) {
              if (context.payload.action === 'opened') {
                // Move to Backlog when opened
                await github.rest.projects.createCard({
                  column_id: 'Backlog',
                  content_id: context.payload.issue.id,
                  content_type: 'Issue'
                });
              }
            } 